"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.localeModuleEn = void 0;
const react_1 = __importDefault(require("react"));
exports.localeModuleEn = {
    documentTitle: 'Find a Nav office - nav.no',
    pageTitle: 'Find a Nav office',
    breadcrumb1: 'Contact us',
    breadcrumb2: 'Find a Nav office',
    ingressLine1: 'Do you not have electronic ID? Or are you trying to find the Nav office on behalf of someone else?',
    ingressLine2: 'If so, you can find a Nav office using a post code or town/city.',
    inputLabel: 'Enter a post code or town/city:',
    inputSubmit: 'Search',
    errorMissingQuery: 'Missing search query',
    errorInvalidQuery: 'Invalid search query',
    errorInvalidPostnr: 'The post code does not exist',
    errorServerError: 'Unknown server error',
    errorInvalidResult: 'Server error: invalid search result',
    errorInputValidationLength: 'Enter at least two letters or a valid post code',
    errorInputValidationPostnr: 'Post code search must be four digits',
    errorInputValidationName: 'Invalid characters in search',
    nameResultHeader: 'Search results for ',
    postnrResultNone: (postnrOgPoststed, adresseQuery) => (react_1.default.createElement(react_1.default.Fragment, null,
        `No Nav office found for `,
        react_1.default.createElement("strong", null, postnrOgPoststed),
        adresseQuery && ` with street name ${adresseQuery}`)),
    postnrResultOne: (postnrOgPoststed) => (react_1.default.createElement(react_1.default.Fragment, null,
        'Nav office for ',
        react_1.default.createElement("strong", null, postnrOgPoststed),
        ':')),
    postnrResultMany: (numHits, postnrOgPoststed, postnr) => (react_1.default.createElement(react_1.default.Fragment, null,
        `${numHits} offices cover `,
        react_1.default.createElement("strong", null, postnrOgPoststed),
        `. You can add a street name and building number to narrow the search, e.g. ${postnr} Example-street 12`)),
    postnrResultPostbox: (postnr, kommuneNavn, numHits) => (react_1.default.createElement(react_1.default.Fragment, null,
        `${postnr} is a post code for PO boxes in `,
        react_1.default.createElement("strong", null, kommuneNavn),
        `. Nav office${Number(numHits) > 1 ? 's' : ''} for this town/city:`)),
    postnrResultServiceBox: (postnr, kommuneNavn, numHits) => (react_1.default.createElement(react_1.default.Fragment, null,
        `${postnr} is a service post code in `,
        react_1.default.createElement("strong", null, kommuneNavn),
        `. Nav office${Number(numHits) > 1 ? 's' : ''} for this town/city:`)),
    postnrResultBydeler: (postnr, kommuneNavn, numHits) => (react_1.default.createElement(react_1.default.Fragment, null,
        'No specific office found for ',
        react_1.default.createElement("strong", null, postnr),
        ' in ',
        react_1.default.createElement("strong", null, kommuneNavn),
        `. ${Number(numHits) > 1 ? 'All ' : ''}Nav office${Number(numHits) > 1 ? 's' : ''} for this town/city:`)),
    nameResultNone: (input) => `No results for "${input}"`,
    nameResultFound: (input, numHits) => `Search results for "${input}" (${numHits}):`,
};
