"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.localeModuleNb = void 0;
const react_1 = __importDefault(require("react"));
exports.localeModuleNb = {
    documentTitle: 'Søk opp Nav-kontor - nav.no',
    pageTitle: 'Søk opp Nav-kontor',
    breadcrumb1: 'Kontakt oss',
    breadcrumb2: 'Søk opp Nav-kontor',
    ingressLine1: 'Mangler du elektronisk ID? Eller skal du finne Nav-kontor på vegne av noen andre?',
    ingressLine2: 'Da kan du søke opp Nav-kontor ved hjelp av postnummer eller sted/by.',
    inputLabel: 'Skriv inn et postnummer eller stedsnavn:',
    inputSubmit: 'Søk',
    errorMissingQuery: 'Mangler søke-streng',
    errorInvalidQuery: 'Feil i søke-streng',
    errorInvalidPostnr: 'Postnummeret finnes ikke',
    errorServerError: 'Ukjent server-feil',
    errorInvalidResult: 'Server-feil: Feil i søke-resultatet',
    errorInputValidationLength: 'Skriv inn minst to bokstaver eller et postnummer',
    errorInputValidationPostnr: 'Postnummer-søk må være fire siffer',
    errorInputValidationName: 'Søket inneholder ugyldige tegn',
    nameResultHeader: 'Søkeresultat for ',
    postnrResultNone: (postnrOgPoststed, adresseQuery) => (react_1.default.createElement(react_1.default.Fragment, null,
        `Ingen Nav-kontor funnet for `,
        react_1.default.createElement("strong", null, postnrOgPoststed),
        adresseQuery && ` med gatenavn ${adresseQuery}`)),
    postnrResultOne: (postnrOgPoststed) => (react_1.default.createElement(react_1.default.Fragment, null,
        'Nav-kontor for ',
        react_1.default.createElement("strong", null, postnrOgPoststed),
        ':')),
    postnrResultMany: (numHits, postnrOgPoststed, postnr) => (react_1.default.createElement(react_1.default.Fragment, null,
        `${numHits} kontorer dekker `,
        react_1.default.createElement("strong", null, postnrOgPoststed),
        `. Du kan legge til gatenavn og husnummer for å spisse søket, f.eks. ${postnr} Eksempelgata 12`)),
    postnrResultPostbox: (postnr, kommuneNavn, numHits) => (react_1.default.createElement(react_1.default.Fragment, null,
        `${postnr} er et postnummer for postbokser i `,
        react_1.default.createElement("strong", null, kommuneNavn),
        ` kommune. Kommunens Nav-kontor${Number(numHits) > 1 ? 'er' : ''}:`)),
    postnrResultServiceBox: (postnr, kommuneNavn, numHits) => (react_1.default.createElement(react_1.default.Fragment, null,
        `${postnr} er et servicepostnummer i `,
        react_1.default.createElement("strong", null, kommuneNavn),
        ` kommune. Kommunens Nav-kontor${Number(numHits) > 1 ? 'er' : ''}:`)),
    postnrResultBydeler: (postnr, kommuneNavn, numHits) => (react_1.default.createElement(react_1.default.Fragment, null,
        'Fant ingen kontor spesifikt tilknyttet ',
        react_1.default.createElement("strong", null, postnr),
        ' i ',
        react_1.default.createElement("strong", null, kommuneNavn),
        ` kommune. ${Number(numHits) > 1 ? 'Alle k' : 'K'}ommunens Nav-kontor${Number(numHits) > 1 ? 'er' : ''}:`)),
    nameResultNone: (input) => `Ingen resultater for "${input}"`,
    nameResultFound: (input, numHits) => `Søkeresultat for "${input}" (${numHits}):`,
};
