"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.localeModuleNn = void 0;
const react_1 = __importDefault(require("react"));
exports.localeModuleNn = {
    documentTitle: 'Søk opp Nav-kontor - nav.no',
    pageTitle: 'Søk opp Nav-kontor',
    breadcrumb1: 'Kontakt oss',
    breadcrumb2: 'Søk opp Nav-kontor',
    ingressLine1: 'Manglar du elektronisk ID? Eller skal du finne Nav-kontor på vegne av nokon andre?',
    ingressLine2: 'Då kan du søke opp Nav-kontor ved hjelp av postnummer eller stad/by.',
    inputLabel: 'Skriv inn eit postnummer eller stadnamn:',
    inputSubmit: 'Søk',
    errorMissingQuery: 'Manglar søke-streng',
    errorInvalidQuery: 'Feil i søke-streng',
    errorInvalidPostnr: 'Postnummeret finns ikkje',
    errorServerError: 'Ukjent server-feil',
    errorInvalidResult: 'Server-feil: Feil i søke-resultatet',
    errorInputValidationLength: 'Skriv inn minst to bokstavar eller eit postnummer',
    errorInputValidationPostnr: 'Postnummer-søk må vere fire siffer',
    errorInputValidationName: 'Søket inneheld ugyldige teikn',
    nameResultHeader: 'Søkeresultat for ',
    postnrResultNone: (postnrOgPoststed, adresseQuery) => (react_1.default.createElement(react_1.default.Fragment, null,
        `Ingen Nav-kontor funne for `,
        react_1.default.createElement("strong", null, postnrOgPoststed),
        adresseQuery && ` med gatenamn ${adresseQuery}`)),
    postnrResultOne: (postnrOgPoststed) => (react_1.default.createElement(react_1.default.Fragment, null,
        'Nav-kontor for ',
        react_1.default.createElement("strong", null, postnrOgPoststed),
        ':')),
    postnrResultMany: (numHits, postnrOgPoststed, postnr) => (react_1.default.createElement(react_1.default.Fragment, null,
        `${numHits} kontor dekker `,
        react_1.default.createElement("strong", null, postnrOgPoststed),
        `. Du kan legge til gatenamn og husnummer for å spisse søket, t.d. ${postnr} Eksempelgata 12`)),
    postnrResultPostbox: (postnr, kommuneNavn, numHits) => (react_1.default.createElement(react_1.default.Fragment, null,
        `${postnr} er eit postnummer for postboksar i `,
        react_1.default.createElement("strong", null, kommuneNavn),
        ` kommune. Kommunens Nav-kontor${Number(numHits) > 1 ? 'er' : ''}:`)),
    postnrResultServiceBox: (postnr, kommuneNavn, numHits) => (react_1.default.createElement(react_1.default.Fragment, null,
        `${postnr} er eit servicepostnummer i `,
        react_1.default.createElement("strong", null, kommuneNavn),
        ` kommune. Kommunens Nav-kontor${Number(numHits) > 1 ? 'er' : ''}:`)),
    postnrResultBydeler: (postnr, kommuneNavn, numHits) => (react_1.default.createElement(react_1.default.Fragment, null,
        'Fant ingen kontor spesifikt knytta til ',
        react_1.default.createElement("strong", null, postnr),
        ' i ',
        react_1.default.createElement("strong", null, kommuneNavn),
        ` kommune. ${Number(numHits) > 1 ? 'Alle k' : 'K'}ommunens Nav-kontor${Number(numHits) > 1 ? 'er' : ''}:`)),
    nameResultNone: (input) => `Ingen resultat for "${input}"`,
    nameResultFound: (input, numHits) => `Søkeresultat for "${input}" (${numHits}):`,
};
