packages:
  - packages/*
catalog:
  '@navikt/nav-dekoratoren-moduler': 4.3.0
  '@types/node': 24.10.1
  '@types/react': 19.3.0
  preact: 10.29.8
  preact-render-to-string: 6.7.0
  react: 19.3.0
  typescript: 6.0.3
  vite: 8.3.1
allowBuilds:
  esbuild: true
  unrs-resolver: true
  '@parcel/watcher': false
minimumReleaseAge: 4320