---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: nav-office-search
  namespace: personbruker
  labels:
    team: personbruker
spec:
  image: {{image}}
  team: personbruker
  port: 3005
  liveness:
    path: {{basePath}}/internal/isAlive
    initialDelay: 5
  readiness:
    path: {{basePath}}/internal/isReady
    initialDelay: 10
  envFrom:
    - secret: nav-office-search
  env:
    - name: NPM_CONFIG_CACHE
      value: /tmp/npm-cache
  replicas:
  {{#with replicas}}
    min: {{min}}
    max: {{max}}
  {{/with}}
  azure:
    application:
      enabled: true
  ingresses:
    - {{ingress}}
  accessPolicy:
    outbound:
      external:
      {{#each outboundExternalHosts as |host|}}
        - host: {{host}}
      {{/each}}
  resources:
    limits:
      cpu: 1000m
      memory: 1000Mi
    requests:
      cpu: 200m
      memory: 256Mi
