---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: nav-office-search
  namespace: personbruker
  labels:
    team: personbruker
spec:
  image: {{image}}
  port: 3005
  liveness:
    path: {{basePath}}/api/internal/isAlive
    initialDelay: 5
  readiness:
    path: {{basePath}}/api/internal/isReady
    initialDelay: 10
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
  envFrom:
    - secret: nav-office-search
  env:
    - name: NPM_CONFIG_CACHE
      value: /tmp/npm-cache
  replicas:
  {{#with replicas}}
    min: {{min}}
    max: {{max}}
  {{/with}}
  azure:
    application:
      enabled: true
  ingresses:
    - {{ingress}}
  accessPolicy:
    outbound:
      external:
      {{#each outboundExternalHosts as |host|}}
        - host: {{host}}
      {{/each}}
      rules:
        - application: nav-dekoratoren
  resources:
  {{#with resources}}
    requests:
      cpu: {{requests.cpu}}
      memory: {{requests.memory}}
    limits:
      memory: {{limits.memory}}
  {{/with}}