---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: nav-office-search
  namespace: personbruker
  labels:
    team: personbruker
spec:
  image: {{image}}
  team: personbruker
  port: 3005
  liveness:
    path: /sok-nav-kontor/api/internal/isAlive
    initialDelay: 10
  readiness:
    path: /sok-nav-kontor/api/internal/isReady
    initialDelay: 10
  envFrom:
    - secret: nav-office-search
  replicas:
    min: 2
    max: 2
  azure:
    application:
      enabled: true
  ingresses:
    - {{ingress}}
  accessPolicy:
    outbound:
      external:
      {{ #each outboundExternalHosts as |host|}}
        - {{host}}
      {{/each}}
  {{accessPolicy}}
  resources:
    limits:
      cpu: '2'
      memory: 1000Mi
    requests:
      cpu: 500m
      memory: 1000Mi
