---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: nav-office-search
  namespace: {{namespace}}
  labels:
    team: personbruker
spec:
  image: {{image}}:{{version}}
  team: personbruker
  port: 3005
  liveness:
    path: /person/finnkontor/api/internal/isAlive
    initialDelay: 10
  readiness:
    path: /person/finnkontor/api/internal/isReady
    initialDelay: 10
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  replicas:
    min: 1
    max: 1
  accessPolicy:
    outbound:
      external:
        - host: dekoratoren.dev.nav.no
        - host: nav-office-search-api.dev.intern.nav.no
  resources:
    limits:
      cpu: '2'
      memory: 256Mi
    requests:
      memory: 256Mi
