---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: nav-office-search
  namespace: {{namespace}}
  labels:
    team: personbruker
spec:
  image: {{image}}:{{version}}
  team: personbruker
  port: 3005
  liveness:
    path: /sok-nav-kontor/api/internal/isAlive
    initialDelay: 10
  readiness:
    path: /sok-nav-kontor/api/internal/isReady
    initialDelay: 10
  ingresses:
    - https://person.dev.nav.no/sok-nav-kontor
  replicas:
    min: 2
    max: 2
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      external:
        - host: dekoratoren.dev.nav.no
        - host: nav-office-search-api.dev-fss-pub.nais.io
      rules:
        - application: nav-office-search-api
          cluster: dev-gcp
          namespace: personbruker
  resources:
    limits:
      cpu: '2'
      memory: 1000Mi
    requests:
      cpu: 500m
      memory: 1000Mi
