name: Deploy to dev
on:
  workflow_dispatch

jobs:
  build-and-deploy:
    uses: ./.github/workflows/build-and-deploy.yml
    permissions:
      contents: "read"
      id-token: "write"
    with:
      environment: dev
      APP_ORIGIN: https://www.ansatt.dev.nav.no
      API_ORIGIN: https://nav-office-search-api.dev-fss-pub.nais.io
      XP_ORIGIN: https://portal-admin-dev.oera.no
      NAVNO_ORIGIN: https://www.ansatt.dev.nav.no
    secrets:
      READER_TOKEN: ${{ secrets.READER_TOKEN }}
      NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
