name: Deploy to prod
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Build and deploy prod
        uses: ./.github/actions/build-and-deploy
        with:
          environment: prod
          APP_ORIGIN: https://www.nav.no
          API_ORIGIN: https://nav-office-search-api.prod-fss-pub.nais.io
          XP_ORIGIN: https://www.nav.no
          NAVNO_ORIGIN: https://www.nav.no
          LOGIN_SESSION_API_URL: https://login.nav.no/oauth2/session
          READER_TOKEN: ${{ secrets.READER_TOKEN }}

  release:
    name: Create a new release
    needs: build-and-deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Generate unique tag name
        run: echo "TAG_NAME=$(date +%s)" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3
        with:
          target_commitish: main
          tag_name: release/prod@${{ env.TAG_NAME }} # Generates a unique tag using timestamp
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }} # This is a PAT with repo permissions
