name: Deploy to prod
on:
  release:
    types: [released]

jobs:
  build-and-deploy:
    if: github.event.release.target_commitish == 'main'
    uses: ./.github/workflows/build-and-deploy.yml
    permissions:
      contents: "read"
      id-token: "write"
    with:
      environment: prod
      APP_ORIGIN: https://www.nav.no
      API_ORIGIN: https://nav-office-search-api.prod-fss-pub.nais.io
      XP_ORIGIN: https://www.nav.no
      NAVNO_ORIGIN: https://www.nav.no
    secrets:
      READER_TOKEN: ${{ secrets.READER_TOKEN }}
      NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
