name: Deploy to dev
on:
  workflow_dispatch

jobs:
  build-and-deploy:
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      environment: dev
      APP_ORIGIN: https://www.dev.nav.no
      API_ORIGIN: https://nav-office-search-api.dev-fss-pub.nais.io
      XP_ORIGIN: https://www.dev.nav.no
    secrets:
      NAIS_DEPLOY_APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
      READER_TOKEN: ${{ secrets.READER_TOKEN }}
