name: Deploy to dev
on: workflow_dispatch

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
        steps:
            - name: Checkout repo
              uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6

            - name: Build and deploy dev
              uses: ./.github/actions/build-and-deploy
              with:
                  environment: dev
                  APP_ORIGIN: https://www.ansatt.dev.nav.no
                  API_ORIGIN: https://nav-office-search-api.dev-fss-pub.nais.io
                  XP_ORIGIN: https://www.dev.nav.no
                  NAVNO_ORIGIN: https://www.ansatt.dev.nav.no
                  READER_TOKEN: ${{ secrets.READER_TOKEN }}
                  project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
                  identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
