name: PR checks
on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  check:
    uses: navikt/navno-ci/.github/workflows/node-build.yml@v1
    with:
      push-image: false
      env-file: |
        ENV=dev
        VITE_APP_ORIGIN=https://www.ansatt.dev.nav.no
        VITE_APP_BASEPATH=/finn-nav-kontor
        VITE_XP_ORIGIN=https://www.dev.nav.no
        VITE_NAVNO_ORIGIN=https://www.ansatt.dev.nav.no
        API_ORIGIN=https://nav-office-search-api.dev-fss-pub.nais.io
        LOGIN_SESSION_API_URL=https://login.ekstern.dev.nav.no/oauth2/session
    secrets: inherit
